### ISSUE TITLE
Inconsistent Trust Anchor parameter names: anchor, trust_anchor_id

### ISSUE THREAD

**Issue by vdzhuvinov** [openid/federation#131]
I identified 2 different parameter names for the Trust Anchor:

- anchor : resolve request
- trust_anchor_id : explicit client registration response

**Comment by zachmann** [comment]
The resolve endpoint uses only `anchor` not `trust_anchor`.

**Comment by selfissued** [comment]
Also, the Subordinate Listing request uses `entity_type` whereas the Resolve request uses `type`.  If we change one of these, it should be the Resolve endpoint, since it shortens the parameter names in an inconsistent way from other endpoints.

**Comment by selfissued** [comment]
And if we're making consistency changes, I suggest changing the claim name `trust_anchor_id` to `trust_anchor`, so we'd be using `trust_anchor` both as the parameter names and as the claim name.

**Comment by peppelinux** [comment]
The resolve endpoint probably used the old parameter nanes taken from other endpoints, these latter changed and this has caused the misalignment

Ok to align them all

Ok to use treu_anchor without _id
Not sure about type vs entity type, because the First doesn't make clear the subject of the type, i'd keep entity_type. Type could be whatever, even the type of the request or of the resolution or anything
