### ISSUE TITLE
Possibly Ambiguous Metadata Policy

### ISSUE THREAD

**Issue by SECtim** [openid/federation#86]
As far as I can see, the following Federation hierarchy is allowed by the specification:
```
    TA_____
   /  \    \
 Im1  Im2  OP
   \  /
   Im3
    |
    RP
```

Furthermore, the specification seems to allow for `Im1` and `Im2` to define conflicting metadata policies for, say, the `openid_relying_party` entity type.
For example, `Im1` may require `token_endpoint_auth_method` to be `private_key_jwt` (i.e., using the `value` operator). Likewise, `Im2` requires the `token_endpoint_auth_method` to be `self_signed_tls_client_auth`.

For example, how would `RP` register at `OP` in this case (Section 12.2)?

Side note: Whether or not `RP` accepts this registration (see Section 12.2.2.2 No. 4) now depends on which of the two possible Trust Chains `RP` uses when checking compliance of the registered metadata with the policy.
Intuitively, the outcome of the compliance check should be deterministic (i.e., disregarding transient issues, an honest OP's registration should always be acceptable to an honest RP).

**Comment by selfissued** [comment]
Related to #7

**Comment by vdzhuvinov** [comment]
If the Im1 and Im2 impose conflicting policies, while being compliant with the TA's policy, the intuitive action for the RP is to raise an issue with its immediate Superiors. Or, if *OpenID Connect Relying Party Metadata Choices 1.0* is supported, use the RP metadata parameter `token_endpoint_auth_methods_supported`.

```
{
  "token_endpoint_auth_methods_supported" : ["private_key_jwt", "self_signed_tls_client_auth"]
}
```
https://openid.net/specs/openid-connect-rp-metadata-choices-1_0-00.html

At today's call we found out that we'll need to update the section "Metadata Policy Principles" - the 6th principle of Determinism.

https://openid.net/specs/openid-federation-1_0.html#section-6.1.1-2.12

Currently it says:

> The resolution and application of metadata policies in a Trust Chain is deterministic. Trust Anchors and Intermediate Entities are thus able to formulate policies that exhibit predictable and reproducible outcomes.

I have a proposal to edit it to say this instead:

> The resolution and application of metadata policies in a **given** Trust Chain is deterministic. Trust Anchors and Intermediate Entities are able to formulate policies that exhibit predictable and reproducible outcomes **for all Subordinate Entities for which a single Trust Chain can be built**.

**Comment by SECtim** [comment]
> If the Im1 and Im2 impose conflicting policies, while being compliant with the TA's policy, the intuitive action for the RP is to raise an issue with its immediate Superiors.

Maybe, but I think the Federation spec should either prevent or give guidance on this scenario:
If the WG agrees that such a situation in an undesirable state, then the spec should say that such conflicting policies are not allowed and who is responsible for enforcing this rule (and how). If, on the other hand, such a situation is intended to be allowed, the spec should give clear guidance on what do to in such a situation (or at least explicitly mention that something like this might happen).

**Comment by zachmann** [comment]
Personally, I would say it's an undesirable state, but something that can (and will) happen; I don't think it's a realistic approach to forbid it, since federation topologies can get arbitrary complex.

I think guidance how to handle such situation is very much needed.

**Comment by vdzhuvinov** [comment]
> the Federation spec should either prevent or give guidance on this scenario:
I'm okay for the spec to include some sort of guidance on this. But I don't want to think about the wording of this :)

There might be ways to prevent this, but it is going to complicate the protocol. This will require authorities to periodically crawl the federation and check the chains.

At first I thought federations will be something elegant and "ideal", but now I see it's going to be more like the Internet, which generally works, despite the occasional networking faults.

**Comment by SECtim** [comment]
> I'm okay for the spec to include some sort of guidance on this. But I don't want to think about the wording of this :)

I guess one way to handle this would be what you already suggested :smile: 

>  raise an issue with its immediate Superiors

... and abort the registration, of course.

**Comment by peppelinux** [comment]
The problem is given by the multiple paths and multiple policies that changes the final metadata.

The question is about who should decide the trust path: the leaf, the anchor, or the trust evaluator?

According to real-world rules, it seems evident that this decision should rest with the trust evaluator, and no one else should have the authority over it.

However, this freedom can be inconvenient in some cases. Instead of proposing solutions in the form of hints or policies, as suggested here, I want to address the root of the problem. The issue is not the freedom of the trust evaluator to choose any path, but rather the freedom of intermediates to publish any metadata policy.

For this reason, **I propose that the decision of which policies should be applied to all subordinates might be best left to the trust anchor alone**. 

As a final solution, we could propose the creation of a new constraint parameter that removes the freedom of subordinates to publish metadata policies, while allowing immediate superiors to publish metadata only for their immediate subordinates.

By removing metadata policies from intermediates and leaving them solely to the trust anchor, we would ensure the security of the framework under the sole authority of the trust anchor, thereby limiting the powers of intermediaries.

Additional policies would still be possible through the use of trust marks.

**Comment by selfissued** [comment]
Per https://github.com/openid/federation/issues/7#issuecomment-2502139489, this resonates with me:
>By all means it will be possible to build bad federations. That does not mean that we should assume that people will, and if they do, that we need to fix it for them. If you build a federation with incompatible paths, shit will happen, regardless of whether this information is there or not. The proper solution is to fix your federation.

**Comment by surfnet-niels** [comment]
While I think deployment guidance is indeed welcome, I do not agree with the notion that one can build a federation as if it is a green field. Policy rules and agreements between parties may already exist, forcing a certain architecture. Furthermore, existing OID Fed based federations, e.g. in different sectors or in different countries, might decide to interfederate, e.g. by adding a TA which has the exiting federations as subordinate. Within the 'local' federation some policies exist because of local regulation or best practice. It is not feasable to just change these within an established federation, to 'fix' the federation. 

While one could ofcause instantiate a new federation with a clean ruleset, if the existig federations are large, the effort involvend to (re)register into a new federation is significant. As mentioned by @zachmann federation in the real world will get complex, and I suspect that will especially be true once OID Fed is deployed for wallet ecosystems.  

It would therefor be very attractive if the protocol facilites the re-use of existign federation. Hence I think TAs should have the 'tooling' to reduce the freedom of the Intermediates as proposed by @peppelinux. As a Leaf can always decide on which TA to use this does not restict the freedom of the Leaf, but it would create more clear Trust paths.

**Comment by lj-raidiam** [comment]
Both the guidance and the TA restrictions are important. We will see various configurations when federations of any pre-existing federations are be built in the future. Unification across the entire network would be ideal and shall be part of the guidance, but will not always be achievable in reality. TA constraints on the other hand will be clear indication of absence of these complexities.

**Comment by Razumain** [comment]
@surfnet-niels and @lj-raidiam I really feel your pain here. I have to admit that I was on your side in the beginning trying to solve these kinds of issues with exceptions and more complexity, but I was finally convinced that I was wrong about that.

I fully understand that there will be islands of different policies, driven by local rules and regulations. But the existing protocol allows that, and there are several tools in the toolbox already to fix the problems that may come up.

In the leading example, the TA is the one that primarily decides what is acceptable in its subordinate federation. Here the TA can easily fix the problem by imposing a policy on Im1 and Im2 that prevents them from forming incompatible policies for Im3. Like setting the common policy rule "subsetOf: ["private_key_jwt"]".

Today I'm convinced that there are multiple ways to make things work using the current toolbox. But I would welcome a description of a use-case where the problem can't be fixed that is worth solving at the expense of a more complexity. I don't think the one presented here is it.
